'use strict';

const i18n = {
  en: {
    nav_title: 'Thai Fancy Weaving — For Sale',
    listing_type: 'Industrial Land & Factory Buildings',
    hero_h1: 'Factory and Industrial Land for Sale — Samut Sakhon, Thailand',
    listing_address: 'No. 54, Moo 4, Setthakit 1 Road (km. 4+100) · Tha Mai, Krathum Baen, Samut Sakhon 74110',
    asking_label: 'Asking Price',
    hero_price: '130,000,000 THB',
    hero_price_usd: '≈ USD $4.0M',
    hero_price_cny: '≈ CNY ¥27.3M',
    contact_email_label: 'Contact',
    hero_cta: 'Send Enquiry',
    tag1: '11 Rai 1 Ngan 13 Sq.Wah',
    tag2: 'Purple Zone',
    tag3: 'Ror Ngor 4 Licence',
    tag4: 'Factory Buildings Included',
    tag5: 'Seller Pays Transfer Fee',
    gallery_title: 'Photos',
    desc_title: 'Property Description',
    desc_p1: 'Industrial land with existing factory buildings and documented infrastructure. Title deed (Chanote), bank valuation report, and sale terms are available for buyer review. The site is located on Setthakit 1 Road with 15.5 metres of direct road frontage and canal frontage (Khlong Tha Rat Prayong) on the western boundary.',
    desc_p2: 'The property carries a Ror Ngor 4 (ร.ง. 4) factory operation licence. Zoning is Purple Zone (ผังเมืองสีม่วง), designated for industrial and warehousing use under the Krathum Baen City Plan B.E. 2562. Transfer fees are paid by the seller based on the Land Department appraisal value.',
    desc_p3: 'The documented factory layout covers 43 labelled functional areas including three weaving buildings, dyeing rooms, sizing machines, worker dormitories, a cafeteria, wastewater treatment infrastructure, and storage warehouses.',
    details_title: 'Property Details',
    spec_address: 'Address',
    spec_address_val: 'No. 54, Moo 4, Setthakit 1 Road (km. 4+100), Tha Mai Sub-district, Krathum Baen District, Samut Sakhon 74110',
    spec_chanote: 'Title Deed',
    spec_chanote_val: 'Chanote No. 54709 — Land No. 124',
    spec_area: 'Total Area',
    spec_area_val: '11 Rai 1 Ngan 13 Sq.Wah (4,513 sq.wah / approx. 18,052 m²)',
    spec_zoning: 'Zoning',
    spec_zoning_val: 'Purple Zone — Industrial & Warehousing (A.2-5), Krathum Baen City Plan B.E. 2562',
    spec_licence: 'Factory Licence',
    spec_licence_val: 'Ror Ngor 4 (ร.ง. 4) — Factory Operation Licence',
    spec_road: 'Road Frontage',
    spec_road_val: '15.5 m on Setthakit 1 Road; western boundary adjoins Khlong Tha Rat Prayong canal',
    spec_buildings: 'Buildings',
    spec_buildings_val: '43 documented functional areas; includes 3 weaving buildings, dyeing, dormitories, offices, and wastewater treatment',
    spec_price: 'Asking Price',
    spec_price_val: '130,000,000 THB (≈ USD $4.0M / CNY ¥27.3M)',
    spec_transfer: 'Transfer Fees',
    spec_transfer_val: 'Paid in full by seller, at Land Dept. appraisal rate',
    spec_commission: 'Commission',
    spec_commission_val: '3% of sale price (paid by seller)',
    val_title: 'Valuation Reference',
    val_note_intro: 'A formal bank valuation was commissioned by Bangkok Bank Public Company Limited in June 2021, using the Cost Approach method. Land Department appraisal figures are used for transfer fee calculation at closing.',
    val_row1_label: 'Asking Price',
    val_row1_val: '130,000,000 THB (≈ USD $4.0M / CNY ¥27.3M)',
    val_row2_label: 'Government Land Dept. Appraisal (June 2021)',
    val_row2_val: '178,071,126 THB',
    val_row3_label: 'Bank Forced-Sale Value (June 2021)',
    val_row3_val: '124,600,000 THB',
    floorplan_title: 'Factory Layout',
    floorplan_note: 'Documented site plan showing 43 labelled functional areas. 170 m × 182 m compound. Frontage on Setthakit 1 Road (bottom of plan).',
    location_title: 'Location',
    location_note_intro: 'Coordinates: 13.673694, 100.28424 — Setthakit 1 Road, Tha Mai, Krathum Baen, Samut Sakhon.',
    distance_title: 'Approximate Driving Distances',
    dist_col_dest: 'Destination',
    dist_col_km: 'Distance',
    dist_col_time: 'Drive Time (approx.)',
    dist1_place: 'Bangkok CBD (Siam / Silom)',
    dist1_km: '~38 km',
    dist1_time: '45–60 min',
    dist2_place: 'Don Mueang Airport (DMK)',
    dist2_km: '~65 km',
    dist2_time: '~1 hr 10 min',
    dist3_place: 'Suvarnabhumi Airport (BKK)',
    dist3_km: '~72 km',
    dist3_time: '~1 hr 15 min',
    dist4_place: 'Laem Chabang Deep Sea Port',
    dist4_km: '~145 km',
    dist4_time: '~2 hrs',
    location_note: 'Note: outbound routes to Suvarnabhumi and Laem Chabang can bypass central Bangkok via the Kanchanaphisek (Southern Ring Road).',
    contact_title: 'Contact',
    contact_sub: 'For documentation requests, site visits, or further information, please contact the owner directly.',
    contact_note: 'Please state that you are enquiring about the Thai Fancy Weaving factory in Samut Sakhon.',
    contact_commission_note: 'Commission: 3% of sale price, paid by seller. Transfer fees paid by seller at Land Department appraisal rate.',
    buyer_notes_title: 'Buyer Notes',
    buyer_note_1: 'Buyers are advised to independently verify title status, encumbrances, building permits, and operational licences with the Land Department and relevant government authorities prior to purchase.',
    buyer_note_2: 'The bank valuation (June 2021) was commissioned for credit assessment purposes. Buyers requiring a current appraisal should commission an independent one.',
    buyer_note_3: 'Distances and exchange rates are approximate. Exchange rates are based on May 2026 rates and are subject to change.',
    buyer_note_4: 'Documentation including the title deed (Chanote), bank valuation report, sale terms sheet, and factory floor plan are available upon written request.',
    footer_copyright: '© 2026 Thai Fancy Weaving Co., Ltd. Property listing.'
  },

  th: {
    nav_title: 'ไทยแฟนซีการทอ — ขายทรัพย์สิน',
    listing_type: 'ที่ดินอุตสาหกรรมพร้อมอาคารโรงงาน',
    hero_h1: 'ขายที่ดินและโรงงานอุตสาหกรรม — จังหวัดสมุทรสาคร ประเทศไทย',
    listing_address: 'เลขที่ 54 หมู่ 4 ถนนเศรษฐกิจ 1 (กม.4+100) · ตำบลท่าไม้ อำเภอกระทุ่มแบน จังหวัดสมุทรสาคร 74110',
    asking_label: 'ราคาขาย',
    hero_price: '130,000,000 บาท',
    hero_price_usd: '≈ USD $4.0M',
    hero_price_cny: '≈ CNY ¥27.3M',
    contact_email_label: 'ติดต่อ',
    hero_cta: 'สอบถาม',
    tag1: '11 ไร่ 1 งาน 13 ตารางวา',
    tag2: 'เขตสีม่วง',
    tag3: 'ใบอนุญาต ร.ง.4',
    tag4: 'มีอาคารโรงงาน',
    tag5: 'ผู้ขายชำระค่าโอน',
    gallery_title: 'ภาพถ่าย',
    desc_title: 'รายละเอียดทรัพย์สิน',
    desc_p1: 'ที่ดินอุตสาหกรรมพร้อมอาคารโรงงานที่มีอยู่และโครงสร้างพื้นฐานที่บันทึกไว้แล้ว โฉนดที่ดิน รายงานการประเมินมูลค่าของธนาคาร และเงื่อนไขการขายพร้อมให้ผู้ซื้อตรวจสอบ ที่ดินตั้งอยู่บนถนนเศรษฐกิจ 1 มีหน้ากว้าง 15.5 เมตร และด้านตะวันตกติดคลองท่าราษฎร์ประโยชน์',
    desc_p2: 'ทรัพย์สินมีใบอนุญาตประกอบกิจการโรงงาน ร.ง. 4 ผังเมืองกำหนดเป็นเขตสีม่วง (อุตสาหกรรมและคลังสินค้า) ตามผังเมืองรวมกระทุ่มแบน พ.ศ. 2562 ค่าโอนที่ดินผู้ขายเป็นผู้ชำระตามราคาประเมินกรมที่ดิน',
    desc_p3: 'แผนผังโรงงานที่บันทึกไว้ครอบคลุม 43 โซนการใช้งานที่ระบุชื่อ รวมถึงโรงทอ 3 หลัง ห้องย้อม เครื่องแต่งเส้นด้าย หอพักคนงาน โรงอาหาร ระบบบำบัดน้ำเสีย และโกดังเก็บสินค้า',
    details_title: 'ข้อมูลทรัพย์สิน',
    spec_address: 'ที่อยู่',
    spec_address_val: 'เลขที่ 54 หมู่ 4 ถนนเศรษฐกิจ 1 (กม.4+100) ตำบลท่าไม้ อำเภอกระทุ่มแบน จังหวัดสมุทรสาคร 74110',
    spec_chanote: 'โฉนดที่ดิน',
    spec_chanote_val: 'โฉนดเลขที่ 54709 — เลขที่ดิน 124',
    spec_area: 'เนื้อที่รวม',
    spec_area_val: '11 ไร่ 1 งาน 13 ตารางวา (4,513 ตร.ว. / ประมาณ 18,052 ตร.ม.)',
    spec_zoning: 'ผังเมือง',
    spec_zoning_val: 'เขตสีม่วง — อุตสาหกรรมและคลังสินค้า (อ.2-5) ผังเมืองรวมกระทุ่มแบน พ.ศ. 2562',
    spec_licence: 'ใบอนุญาตโรงงาน',
    spec_licence_val: 'ใบอนุญาตประกอบกิจการโรงงาน ร.ง. 4',
    spec_road: 'หน้าติดถนน',
    spec_road_val: 'กว้าง 15.5 ม. ติดถนนเศรษฐกิจ 1; ด้านตะวันตกติดคลองท่าราษฎร์ประโยชน์',
    spec_buildings: 'อาคาร',
    spec_buildings_val: '43 โซนการใช้งาน; รวมถึงโรงทอ 3 หลัง ห้องย้อม หอพัก สำนักงาน และระบบบำบัดน้ำเสีย',
    spec_price: 'ราคาขาย',
    spec_price_val: '130,000,000 บาท (≈ USD $4.0M / CNY ¥27.3M)',
    spec_transfer: 'ค่าโอน',
    spec_transfer_val: 'ผู้ขายชำระเต็มจำนวน ตามราคาประเมินกรมที่ดิน',
    spec_commission: 'ค่านายหน้า',
    spec_commission_val: '3% ของราคาขาย (ผู้ขายชำระ)',
    val_title: 'ข้อมูลอ้างอิงการประเมิน',
    val_note_intro: 'การประเมินมูลค่าทรัพย์สินอย่างเป็นทางการได้รับมอบหมายจากธนาคารกรุงเทพ จำกัด (มหาชน) ในเดือนมิถุนายน 2564 โดยใช้วิธีคิดจากต้นทุน ราคาประเมินกรมที่ดินใช้สำหรับคำนวณค่าธรรมเนียมการโอน',
    val_row1_label: 'ราคาขาย',
    val_row1_val: '130,000,000 บาท (≈ USD $4.0M / CNY ¥27.3M)',
    val_row2_label: 'ราคาประเมินกรมที่ดิน (มิ.ย. 2564)',
    val_row2_val: '178,071,126 บาท',
    val_row3_label: 'มูลค่าบังคับขายของธนาคาร (มิ.ย. 2564)',
    val_row3_val: '124,600,000 บาท',
    floorplan_title: 'แผนผังโรงงาน',
    floorplan_note: 'แผนผังที่บันทึกไว้แสดง 43 โซนการใช้งานพร้อมป้ายชื่อ พื้นที่ 170 × 182 เมตร หน้าที่ดินติดถนนเศรษฐกิจ 1 (ด้านล่างของแผนผัง)',
    location_title: 'ที่ตั้ง',
    location_note_intro: 'พิกัด: 13.673694, 100.28424 — ถนนเศรษฐกิจ 1 ตำบลท่าไม้ อำเภอกระทุ่มแบน จังหวัดสมุทรสาคร',
    distance_title: 'ระยะทางขับรถโดยประมาณ',
    dist_col_dest: 'ปลายทาง',
    dist_col_km: 'ระยะทาง',
    dist_col_time: 'เวลาเดินทาง (โดยประมาณ)',
    dist1_place: 'ใจกลางกรุงเทพฯ (สยาม / สีลม)',
    dist1_km: '~38 กม.',
    dist1_time: '45–60 นาที',
    dist2_place: 'สนามบินดอนเมือง (DMK)',
    dist2_km: '~65 กม.',
    dist2_time: '~1 ชม. 10 นาที',
    dist3_place: 'สนามบินสุวรรณภูมิ (BKK)',
    dist3_km: '~72 กม.',
    dist3_time: '~1 ชม. 15 นาที',
    dist4_place: 'ท่าเรือแหลมฉบัง',
    dist4_km: '~145 กม.',
    dist4_time: '~2 ชม.',
    location_note: 'หมายเหตุ: เส้นทางไปสุวรรณภูมิและแหลมฉบังสามารถหลีกเลี่ยงกรุงเทพฯ ได้ผ่านถนนวงแหวนกาญจนาภิเษก (ทิศใต้)',
    contact_title: 'ติดต่อ',
    contact_sub: 'สำหรับการขอเอกสาร นัดชมสถานที่ หรือสอบถามข้อมูลเพิ่มเติม กรุณาติดต่อเจ้าของโดยตรง',
    contact_note: 'กรุณาระบุว่าสนใจโรงงานไทยแฟนซีการทอ จังหวัดสมุทรสาคร',
    contact_commission_note: 'ค่านายหน้า: 3% ของราคาขาย (ผู้ขายชำระ) ค่าโอนคิดตามราคาประเมินกรมที่ดิน',
    buyer_notes_title: 'หมายเหตุสำหรับผู้ซื้อ',
    buyer_note_1: 'ผู้ซื้อควรตรวจสอบสถานะโฉนด ภาระผูกพัน ใบอนุญาตก่อสร้าง และใบอนุญาตประกอบกิจการกับกรมที่ดินและหน่วยงานที่เกี่ยวข้องอย่างอิสระก่อนการซื้อ',
    buyer_note_2: 'การประเมินมูลค่าของธนาคาร (มิ.ย. 2564) ดำเนินการเพื่อวัตถุประสงค์การพิจารณาสินเชื่อ ผู้ซื้อที่ต้องการการประเมินปัจจุบันควรว่าจ้างผู้ประเมินอิสระ',
    buyer_note_3: 'ระยะทางและอัตราแลกเปลี่ยนเป็นค่าประมาณ อัตราแลกเปลี่ยนอ้างอิงจากเดือนพฤษภาคม 2569 และอาจเปลี่ยนแปลงได้',
    buyer_note_4: 'เอกสารรวมถึงโฉนดที่ดิน รายงานการประเมิน เงื่อนไขการขาย และแผนผังโรงงาน พร้อมให้ตรวจสอบตามคำขอเป็นลายลักษณ์อักษร',
    footer_copyright: '© 2569 บริษัท ไทยแฟนซีการทอ จำกัด ประกาศขายทรัพย์สิน'
  },

  zh: {
    nav_title: '泰国织布工厂 — 出售',
    listing_type: '工业用地及厂房建筑',
    hero_h1: '工厂及工业用地出售 — 泰国沙没萨空府',
    listing_address: '泰国沙没萨空府 Krathum Baen 区 Tha Mai 分区 Setthakit 1 路54号（4+100公里处）邮编74110',
    asking_label: '要价',
    hero_price: '130,000,000 泰铢',
    hero_price_usd: '≈ 美元 $400万',
    hero_price_cny: '≈ 人民币 ¥2730万',
    contact_email_label: '联系方式',
    hero_cta: '发送询价',
    tag1: '11莱1恩13平方哇',
    tag2: '紫色工业区',
    tag3: 'ร.ง.4 工厂许可证',
    tag4: '含厂房建筑',
    tag5: '卖方承担过户费',
    gallery_title: '实地照片',
    desc_title: '房产描述',
    desc_p1: '工业用地，现有厂房建筑及有据可查的基础设施。土地证（Chanote）、银行评估报告及出售条款可供买方审阅。地块位于 Setthakit 1 路，临街宽度15.5米，西侧临 Khlong Tha Rat Prayong 运河。',
    desc_p2: '该地产持有 Ror Ngor 4（ร.ง.4）工厂经营许可证。土地规划属紫色区域（工业及仓储用地），依据2019年 Krathum Baen 城市规划划定。过户费由卖方按土地部评估价承担。',
    desc_p3: '有记录的工厂平面图涵盖43个已标注功能区域，包括三座织布厂房、染色车间、上浆机、工人宿舍、食堂、污水处理设施及仓储区。',
    details_title: '房产信息',
    spec_address: '地址',
    spec_address_val: '泰国沙没萨空府 Krathum Baen 区 Tha Mai 分区 Setthakit 1 路54号（4+100公里处）邮编74110',
    spec_chanote: '土地证',
    spec_chanote_val: 'Chanote 编号54709 — 地块编号124',
    spec_area: '总面积',
    spec_area_val: '11莱1恩13平方哇（4,513平方哇 / 约18,052平方米）',
    spec_zoning: '土地规划',
    spec_zoning_val: '紫色区域 — 工业及仓储（A.2-5），Krathum Baen 城市规划2019年版',
    spec_licence: '工厂许可证',
    spec_licence_val: 'Ror Ngor 4（ร.ง.4）工厂经营许可证',
    spec_road: '临街情况',
    spec_road_val: '临 Setthakit 1 路宽15.5米；西侧临 Khlong Tha Rat Prayong 运河',
    spec_buildings: '建筑物',
    spec_buildings_val: '43个有记录的功能区域；含3座织布厂房、染色车间、宿舍、办公室及污水处理设施',
    spec_price: '要价',
    spec_price_val: '130,000,000泰铢（≈ 美元 $400万 / 人民币 ¥2730万）',
    spec_transfer: '过户费用',
    spec_transfer_val: '由卖方全额承担，按土地部评估价计算',
    spec_commission: '中介佣金',
    spec_commission_val: '成交价的3%（由卖方支付）',
    val_title: '估值参考',
    val_note_intro: '2021年6月，受曼谷银行股份有限公司委托，以成本法对该资产进行了正式银行评估。土地部评估价用于计算过户时的税费。',
    val_row1_label: '要价',
    val_row1_val: '130,000,000泰铢（≈ 美元 $400万 / 人民币 ¥2730万）',
    val_row2_label: '政府土地部评估价（2021年6月）',
    val_row2_val: '178,071,126泰铢',
    val_row3_label: '银行强制出售价值（2021年6月）',
    val_row3_val: '124,600,000泰铢',
    floorplan_title: '工厂平面图',
    floorplan_note: '有记录的现场平面图标注了43个功能区域。园区170×182米，正面临 Setthakit 1 路（平面图下方）。',
    location_title: '地理位置',
    location_note_intro: '坐标：13.673694, 100.28424 — Setthakit 1 路，Tha Mai，Krathum Baen，沙没萨空府。',
    distance_title: '至主要目的地驾车距离（近似值）',
    dist_col_dest: '目的地',
    dist_col_km: '距离',
    dist_col_time: '驾车时间（近似）',
    dist1_place: '曼谷市中心（暹罗 / 是隆）',
    dist1_km: '约38公里',
    dist1_time: '45–60分钟',
    dist2_place: '廊曼国际机场（DMK）',
    dist2_km: '约65公里',
    dist2_time: '约1小时10分',
    dist3_place: '素万那普国际机场（BKK）',
    dist3_km: '约72公里',
    dist3_time: '约1小时15分',
    dist4_place: '林查班深水港',
    dist4_km: '约145公里',
    dist4_time: '约2小时',
    location_note: '注：前往素万那普机场和林查班港可经由南部环城公路（Kanchanaphisek）绕过曼谷市区。',
    contact_title: '联系方式',
    contact_sub: '如需索取文件、安排实地参观或进一步了解详情，请直接联系业主。',
    contact_note: '请注明您咨询的是沙没萨空府的泰国织布工厂。',
    contact_commission_note: '佣金：成交价3%，由卖方支付。过户费按土地部评估价由卖方承担。',
    buyer_notes_title: '买方须知',
    buyer_note_1: '建议买方在购买前，就产权状态、抵押情况、建筑许可证及经营许可证向土地部及相关政府部门进行独立核实。',
    buyer_note_2: '银行评估（2021年6月）系为信贷审批目的委托进行。需要最新评估报告的买方应自行委托独立评估师。',
    buyer_note_3: '距离及汇率均为近似值。汇率参考2026年5月数据，可能随时变动。',
    buyer_note_4: '相关文件包括土地证（Chanote）、银行评估报告、出售条款说明及工厂平面图，可应书面请求提供。',
    footer_copyright: '© 2026 Thai Fancy Weaving Co., Ltd. 房产挂牌信息。'
  }
};

let currentLang = 'en';

function setLang(lang) {
  if (!i18n[lang]) return;
  currentLang = lang;
  document.documentElement.lang = lang === 'zh' ? 'zh-Hans' : lang;

  document.querySelectorAll('[data-i18n]').forEach(function(el) {
    const key = el.getAttribute('data-i18n');
    if (i18n[lang][key] !== undefined) {
      el.textContent = i18n[lang][key];
    }
  });

  document.querySelectorAll('.lang-btn').forEach(function(btn) {
    btn.classList.remove('active');
  });
  const btn = document.getElementById('lang-' + lang);
  if (btn) btn.classList.add('active');

  try { localStorage.setItem('preferred-lang', lang); } catch (e) {}
}

(function init() {
  let saved = 'en';
  try { saved = localStorage.getItem('preferred-lang') || 'en'; } catch (e) {}
  if (i18n[saved]) setLang(saved);
})();
