'use strict';

const i18n = {
  en: {
    nav_title: 'Thai Fancy Weaving',
    hero_location: 'Samut Sakhon Province, Thailand',
    hero_h1: 'Thai Fancy Weaving Co., Ltd.',
    hero_tagline: 'Fully Operational Textile Factory — For Sale',
    hero_price: '130,000,000 THB',
    hero_price_usd: '≈ USD $4.0M',
    hero_price_cny: '≈ CNY ¥27.3M',
    hero_tag1: '11 Rai Industrial Land',
    hero_tag2: 'Purple Zone',
    hero_tag3: 'Ror Ngor 4 Licence',
    hero_tag4: 'Currently Operating',
    hero_cta: 'Enquire Now',
    highlights_title: 'Investment Highlights',
    h1_value: '11 Rai 1 Ngan',
    h1_label: 'Land Area',
    h1_sub: '4,513 sq.wah / 18,052 m²',
    h2_value: 'Purple Zone',
    h2_label: 'Zoning',
    h2_sub: 'Industrial & Warehousing',
    h3_value: 'Ror Ngor 4',
    h3_label: 'Factory Licence',
    h3_sub: 'Active — Fully Transferable',
    h4_value: '15.5 Metres',
    h4_label: 'Road Frontage',
    h4_sub: 'Direct on Setthakit 1 Road',
    h5_value: '43 Areas',
    h5_label: 'Functional Zones',
    h5_sub: '3 weaving plants, dyeing, dorms + more',
    h6_value: 'Seller Pays',
    h6_label: 'Transfer Fees',
    h6_sub: 'Based on Land Dept. appraisal',
    about_title: 'About the Property',
    about_p1: 'Thai Fancy Weaving Co., Ltd. is a fully operational textile manufacturing facility set on 11 rai of prime industrial land in Samut Sakhon Province, located directly on Setthakit 1 Road with 15.5 metres of main-road frontage. The compound includes three weaving factories, dyeing facilities, sizing machines, worker dormitories, a cafeteria, wastewater treatment infrastructure, and extensive warehouse storage — 43 distinct functional areas in total.',
    about_p2: 'The property sits in Krathum Baen District\'s Purple Zone (ผังเมืองสีม่วง), zoned exclusively for industrial and warehousing use. Its most significant asset beyond the physical infrastructure is an active Ror Ngor 4 (ร.ง. 4) factory operation licence — a government permit that can take years and significant capital to obtain from scratch. This licence transfers with the property.',
    about_p3: 'The canal frontage (Khlong Tha Rat Prayong) along the western boundary adds additional utility and character to the site.',
    specs_title: 'Property Specifications',
    spec_address: 'Address',
    spec_address_val: 'No. 54, Moo 4, Setthakit 1 Road (km. 4+100), Tha Mai Sub-district, Krathum Baen District, Samut Sakhon 74110',
    spec_chanote: 'Title Deed',
    spec_chanote_val: 'Chanote No. 54709 — Land No. 124',
    spec_area: 'Total Area',
    spec_area_val: '11 Rai 1 Ngan 13 Sq.Wah (4,513 sq.wah / approx. 18,052 m²)',
    spec_zoning: 'Zoning',
    spec_zoning_val: 'Purple Zone — Industrial & Warehousing (A.2-5), Krathum Baen City Plan B.E. 2562',
    spec_licence: 'Factory Licence',
    spec_licence_val: 'Active Ror Ngor 4 (ร.ง. 4) — Factory Operation Licence',
    spec_road: 'Road Frontage',
    spec_road_val: '15.5 m on Setthakit 1 Road; canal frontage (Khlong Tha Rat Prayong) on west boundary',
    spec_price: 'Asking Price',
    spec_price_val: '130,000,000 THB (≈ USD $4.0M / CNY ¥27.3M)',
    spec_appraisal: 'Govt. Appraisal',
    spec_appraisal_val: '178,071,126 THB — asking is 27% below official appraisal',
    spec_transfer: 'Transfer Fees',
    spec_transfer_val: 'Paid in full by seller, at Land Dept. appraisal rate',
    spec_commission: 'Commission',
    spec_commission_val: '3% of sale price (paid by seller)',
    valuation_title: 'Pricing in Context',
    valuation_sub: 'The asking price represents exceptional value relative to the official government appraisal.',
    val_asking: 'Asking Price',
    val_asking_amt: '130,000,000 THB',
    val_appraisal: 'Govt. Appraisal',
    val_appraisal_amt: '178,071,126 THB',
    val_note: 'Asking price is 27% below the official government Land Department appraisal value of 178,071,126 THB.',
    floorplan_title: 'Factory Layout',
    floorplan_sub: '43 functional zones across a 170 m × 182 m compound — fully mapped and documented.',
    gallery_title: 'Property Photos',
    gallery_sub: 'Road frontage on Setthakit 1 Road, 15.5 m entrance gate, and canal frontage.',
    location_title: 'Location',
    location_sub: 'Strategically located between Bangkok and Thailand\'s key logistics corridors.',
    distance_title: 'Distance to Key Hubs',
    dist1_place: 'Bangkok CBD (Siam / Silom)',
    dist1_km: '~38 km',
    dist1_time: '45–60 min',
    dist2_place: 'Don Mueang Airport (DMK)',
    dist2_km: '~65 km',
    dist2_time: '~1 hr 10 min',
    dist3_place: 'Suvarnabhumi Airport (BKK)',
    dist3_km: '~72 km',
    dist3_time: '~1 hr 15 min',
    dist4_place: 'Laem Chabang Deep Sea Port',
    dist4_km: '~145 km',
    dist4_time: '~2 hrs',
    location_note: 'Outbound logistics to Thailand\'s Eastern Seaboard can bypass central Bangkok traffic via the Kanchanaphisek Southern Ring Road, improving effective transit times to Suvarnabhumi and Laem Chabang.',
    contact_title: 'Contact & Enquiries',
    contact_sub: 'For site visits, documentation requests, or further information, please contact directly.',
    contact_email_label: 'Email',
    contact_note: 'Please mention you are enquiring about the Thai Fancy Weaving factory in Samut Sakhon.',
    contact_commission_note: 'Commission: 3% of sale price, paid by seller. Transfer fees paid by seller at Land Department appraisal rate.',
    footer_disclaimer: 'All figures are approximate. Exchange rates are indicative and subject to change. The government appraisal was conducted in June 2021; current market values should be independently verified. Prospective buyers are advised to conduct independent legal and financial due diligence. Full documentation available upon request.',
    footer_copyright: '© 2026 Thai Fancy Weaving Co., Ltd. Property listing.'
  },

  th: {
    nav_title: 'ไทยแฟนซีการทอ',
    hero_location: 'จังหวัดสมุทรสาคร ประเทศไทย',
    hero_h1: 'บริษัท ไทยแฟนซีการทอ จำกัด',
    hero_tagline: 'โรงงานทอผ้าที่กำลังดำเนินกิจการ — ขาย',
    hero_price: '130,000,000 บาท',
    hero_price_usd: '≈ USD $4.0M',
    hero_price_cny: '≈ CNY ¥27.3M',
    hero_tag1: 'ที่ดินอุตสาหกรรม 11 ไร่',
    hero_tag2: 'เขตสีม่วง',
    hero_tag3: 'ใบอนุญาต ร.ง.4',
    hero_tag4: 'กำลังดำเนินกิจการ',
    hero_cta: 'ติดต่อสอบถาม',
    highlights_title: 'จุดเด่นการลงทุน',
    h1_value: '11 ไร่ 1 งาน',
    h1_label: 'เนื้อที่ดิน',
    h1_sub: '4,513 ตร.ว. / 18,052 ตร.ม.',
    h2_value: 'เขตสีม่วง',
    h2_label: 'ผังเมือง',
    h2_sub: 'อุตสาหกรรมและคลังสินค้า',
    h3_value: 'ร.ง. 4',
    h3_label: 'ใบอนุญาตโรงงาน',
    h3_sub: 'มีผลบังคับใช้ — โอนได้',
    h4_value: '15.5 เมตร',
    h4_label: 'หน้าติดถนน',
    h4_sub: 'ติดถนนเศรษฐกิจ 1 โดยตรง',
    h5_value: '43 พื้นที่',
    h5_label: 'โซนการใช้งาน',
    h5_sub: 'โรงทอ 3 หลัง ห้องย้อม หอพัก และอื่นๆ',
    h6_value: 'ผู้ขายชำระ',
    h6_label: 'ค่าโอน',
    h6_sub: 'คิดตามราคาประเมินกรมที่ดิน',
    about_title: 'รายละเอียดทรัพย์สิน',
    about_p1: 'บริษัท ไทยแฟนซีการทอ จำกัด เป็นโรงงานทอผ้าที่กำลังดำเนินกิจการอยู่บนที่ดินอุตสาหกรรมชั้นเยี่ยม 11 ไร่ ในจังหวัดสมุทรสาคร ตั้งอยู่ริมถนนเศรษฐกิจ 1 โดยตรง มีหน้าที่ดินกว้าง 15.5 เมตร ภายในมีโรงทอ 3 หลัง สิ่งอำนวยความสะดวกสำหรับการย้อมผ้า เครื่องแต่งเส้นด้าย หอพักคนงาน โรงอาหาร ระบบบำบัดน้ำเสีย และพื้นที่จัดเก็บสินค้า รวม 43 โซนการใช้งาน',
    about_p2: 'ทรัพย์สินตั้งอยู่ในเขตสีม่วง (ผังเมืองอุตสาหกรรมและคลังสินค้า) อำเภอกระทุ่มแบน สินทรัพย์ที่มีมูลค่าสูงสุดคือใบอนุญาตประกอบกิจการโรงงาน ร.ง. 4 ที่ยังมีผลบังคับใช้ ซึ่งต้องใช้เวลาและทรัพยากรมากในการขอใหม่จากต้นทาง ใบอนุญาตนี้โอนพร้อมกับทรัพย์สิน',
    about_p3: 'ด้านตะวันตกของที่ดินติดคลองท่าราษฎร์ประโยชน์ ซึ่งเพิ่มคุณค่าและความเป็นเอกลักษณ์ให้กับทรัพย์สิน',
    specs_title: 'ข้อมูลจำเพาะทรัพย์สิน',
    spec_address: 'ที่อยู่',
    spec_address_val: 'เลขที่ 54 หมู่ 4 ถนนเศรษฐกิจ 1 กม.4+100 ตำบลท่าไม้ อำเภอกระทุ่มแบน จังหวัดสมุทรสาคร 74110',
    spec_chanote: 'โฉนดที่ดิน',
    spec_chanote_val: 'โฉนดเลขที่ 54709 — เลขที่ดิน 124',
    spec_area: 'เนื้อที่รวม',
    spec_area_val: '11 ไร่ 1 งาน 13 ตารางวา (4,513 ตร.ว. / ประมาณ 18,052 ตร.ม.)',
    spec_zoning: 'ผังเมือง',
    spec_zoning_val: 'เขตสีม่วง — อุตสาหกรรมและคลังสินค้า (อ.2-5) ผังเมืองรวมกระทุ่มแบน พ.ศ. 2562',
    spec_licence: 'ใบอนุญาตโรงงาน',
    spec_licence_val: 'ใบอนุญาตประกอบกิจการโรงงาน ร.ง. 4 ที่ยังมีผลบังคับใช้',
    spec_road: 'หน้าติดถนน',
    spec_road_val: 'กว้าง 15.5 ม. ติดถนนเศรษฐกิจ 1; ด้านตะวันตกติดคลองท่าราษฎร์ประโยชน์',
    spec_price: 'ราคาขาย',
    spec_price_val: '130,000,000 บาท (≈ USD $4.0M / CNY ¥27.3M)',
    spec_appraisal: 'ราคาประเมินราชการ',
    spec_appraisal_val: '178,071,126 บาท — ราคาขายต่ำกว่าราคาประเมิน 27%',
    spec_transfer: 'ค่าโอน',
    spec_transfer_val: 'ผู้ขายชำระเต็มจำนวน คิดตามราคาประเมินกรมที่ดิน',
    spec_commission: 'ค่านายหน้า',
    spec_commission_val: '3% ของราคาขาย (ผู้ขายชำระ)',
    valuation_title: 'บริบทราคา',
    valuation_sub: 'ราคาขายสะท้อนมูลค่าที่ยอดเยี่ยมเมื่อเทียบกับราคาประเมินราชการ',
    val_asking: 'ราคาขาย',
    val_asking_amt: '130,000,000 บาท',
    val_appraisal: 'ราคาประเมินราชการ',
    val_appraisal_amt: '178,071,126 บาท',
    val_note: 'ราคาขายต่ำกว่าราคาประเมินกรมที่ดิน 178,071,126 บาท ถึง 27%',
    floorplan_title: 'แผนผังโรงงาน',
    floorplan_sub: '43 โซนการใช้งานภายในพื้นที่ 170 × 182 เมตร — จัดทำแผนผังและเอกสารไว้ครบถ้วน',
    gallery_title: 'ภาพถ่ายทรัพย์สิน',
    gallery_sub: 'หน้าถนนเศรษฐกิจ 1 ทางเข้ากว้าง 15.5 ม. และริมคลอง',
    location_title: 'ที่ตั้ง',
    location_sub: 'ทำเลกลยุทธ์ระหว่างกรุงเทพฯ และเส้นทางโลจิสติกส์สำคัญของไทย',
    distance_title: 'ระยะทางสู่จุดสำคัญ',
    dist1_place: 'ใจกลางกรุงเทพฯ (สยาม / สีลม)',
    dist1_km: '~38 กม.',
    dist1_time: '45–60 นาที',
    dist2_place: 'สนามบินดอนเมือง (DMK)',
    dist2_km: '~65 กม.',
    dist2_time: '~1 ชม. 10 นาที',
    dist3_place: 'สนามบินสุวรรณภูมิ (BKK)',
    dist3_km: '~72 กม.',
    dist3_time: '~1 ชม. 15 นาที',
    dist4_place: 'ท่าเรือแหลมฉบัง',
    dist4_km: '~145 กม.',
    dist4_time: '~2 ชม.',
    location_note: 'การขนส่งออกไปยังชายฝั่งทะเลตะวันออกสามารถหลีกเลี่ยงการจราจรกรุงเทพฯ ได้โดยใช้ถนนวงแหวนกาญจนาภิเษก ช่วยลดเวลาขนส่งไปยังสุวรรณภูมิและแหลมฉบัง',
    contact_title: 'ติดต่อสอบถาม',
    contact_sub: 'สำหรับการนัดชมสถานที่ ขอเอกสาร หรือสอบถามข้อมูลเพิ่มเติม กรุณาติดต่อโดยตรง',
    contact_email_label: 'อีเมล',
    contact_note: 'กรุณาระบุว่าสนใจโรงงานไทยแฟนซีการทอ จังหวัดสมุทรสาคร',
    contact_commission_note: 'ค่านายหน้า: 3% ของราคาขาย (ผู้ขายชำระ) ค่าโอนคิดตามราคาประเมินกรมที่ดิน',
    footer_disclaimer: 'ตัวเลขทั้งหมดเป็นค่าประมาณ อัตราแลกเปลี่ยนอาจเปลี่ยนแปลงได้ การประเมินราคาดำเนินการในเดือนมิถุนายน 2564 ผู้ซื้อควรตรวจสอบมูลค่าตลาดปัจจุบันอย่างอิสระ ควรดำเนินการตรวจสอบทางกฎหมายและการเงินอย่างอิสระ เอกสารฉบับเต็มพร้อมให้ตรวจสอบตามคำขอ',
    footer_copyright: '© 2026 บริษัท ไทยแฟนซีการทอ จำกัด ประกาศขายทรัพย์สิน'
  },

  zh: {
    nav_title: '泰国织布工厂',
    hero_location: '泰国沙没萨空府',
    hero_h1: '泰国织布有限公司',
    hero_tagline: '正在运营的纺织工厂 — 现正出售',
    hero_price: '1.3亿泰铢',
    hero_price_usd: '≈ 美元 $400万',
    hero_price_cny: '≈ 人民币 ¥2730万',
    hero_tag1: '11莱工业用地',
    hero_tag2: '紫色工业区',
    hero_tag3: 'ร.ง.4 工厂许可证',
    hero_tag4: '工厂正常运营中',
    hero_cta: '立即咨询',
    highlights_title: '投资亮点',
    h1_value: '11莱1恩',
    h1_label: '占地面积',
    h1_sub: '4,513平方哇 / 18,052平方米',
    h2_value: '紫色区域',
    h2_label: '土地规划',
    h2_sub: '工业及仓储用地',
    h3_value: 'ร.ง.4 许可证',
    h3_label: '工厂许可证',
    h3_sub: '有效期内 — 可随产权转让',
    h4_value: '15.5米',
    h4_label: '临街宽度',
    h4_sub: '紧靠 Setthakit 1 号主干道',
    h5_value: '43个区域',
    h5_label: '功能区域',
    h5_sub: '3座织布厂、染色、宿舍等',
    h6_value: '卖方全额承担',
    h6_label: '过户费用',
    h6_sub: '按土地部评估价计算',
    about_title: '房产详情',
    about_p1: '泰国织布有限公司（Thai Fancy Weaving Co., Ltd.）是一家正在运营的纺织生产基地，占地11莱优质工业用地，位于泰国沙没萨空府，紧邻 Setthakit 1 号主干道，临街宽度15.5米。园区内设有三座织布厂、染色车间、上浆机、工人宿舍、食堂、污水处理设施及仓储区域，共43个功能区域。',
    about_p2: '该地块位于 Krathum Baen 区紫色区域（工业及仓储专用区）。最核心价值在于持有有效的工厂经营许可证（ร.ง.4）——此类许可证从零申请通常需要数年时间及大量资金，极具稀缺性，且可随产权一同转让给买方。',
    about_p3: '地块西侧紧靠 Khlong Tha Rat Prayong 运河，为该地产增添了独特的实用价值与特色。',
    specs_title: '房产规格',
    spec_address: '地址',
    spec_address_val: '泰国沙没萨空府 Krathum Baen 区 Tha Mai 分区 Setthakit 1 路54号（4+100公里处）邮编74110',
    spec_chanote: '土地证',
    spec_chanote_val: 'Chanote 编号54709 — 地块编号124',
    spec_area: '总面积',
    spec_area_val: '11莱1恩13平方哇（4,513平方哇 / 约18,052平方米）',
    spec_zoning: '土地规划',
    spec_zoning_val: '紫色区域 — 工业及仓储（A.2-5），Krathum Baen 城市规划2019年版',
    spec_licence: '工厂许可证',
    spec_licence_val: '有效 ร.ง.4 工厂经营许可证',
    spec_road: '临街情况',
    spec_road_val: '临 Setthakit 1 路宽15.5米；西侧临 Khlong Tha Rat Prayong 运河',
    spec_price: '要价',
    spec_price_val: '130,000,000泰铢（≈ 美元 $400万 / 人民币 ¥2730万）',
    spec_appraisal: '政府评估价',
    spec_appraisal_val: '178,071,126泰铢 — 要价较评估价低27%',
    spec_transfer: '过户费用',
    spec_transfer_val: '卖方全额承担，按土地部评估价计算',
    spec_commission: '中介佣金',
    spec_commission_val: '成交价的3%（由卖方支付）',
    valuation_title: '定价分析',
    valuation_sub: '相较于官方政府评估价，要价极具吸引力。',
    val_asking: '要价',
    val_asking_amt: '1.3亿泰铢',
    val_appraisal: '政府评估价',
    val_appraisal_amt: '1.78亿泰铢',
    val_note: '要价较官方土地部评估价178,071,126泰铢低27%。',
    floorplan_title: '工厂平面图',
    floorplan_sub: '170×182米园区内43个功能区域，完整记录在案。',
    gallery_title: '实地照片',
    gallery_sub: '临 Setthakit 1 路街景、15.5米入口大门及运河临界面。',
    location_title: '地理位置',
    location_sub: '战略性地位于曼谷与泰国主要物流走廊之间。',
    distance_title: '至主要枢纽距离',
    dist1_place: '曼谷市中心（暹罗 / 是隆）',
    dist1_km: '约38公里',
    dist1_time: '45–60分钟',
    dist2_place: '廊曼国际机场（DMK）',
    dist2_km: '约65公里',
    dist2_time: '约1小时10分钟',
    dist3_place: '素万那普国际机场（BKK）',
    dist3_km: '约72公里',
    dist3_time: '约1小时15分钟',
    dist4_place: '林查班深水港',
    dist4_km: '约145公里',
    dist4_time: '约2小时',
    location_note: '前往泰国东部海岸的物流运输可经由南部环城公路（Kanchanaphisek）绕开曼谷市区交通，有效缩短至素万那普机场和林查班港的运输时间。',
    contact_title: '联系与咨询',
    contact_sub: '如需参观厂区、索取相关文件或进一步了解详情，请直接联系。',
    contact_email_label: '电子邮件',
    contact_note: '请注明您咨询的是沙没萨空府泰国织布工厂。',
    contact_commission_note: '佣金：成交价3%，由卖方支付。过户费按土地部评估价计算，由卖方承担。',
    footer_disclaimer: '所有数据均为近似值。汇率仅供参考，随时可能变动。政府评估于2021年6月进行，当前市场价值应由买方独立核实。建议潜在买家进行独立的法律及财务尽职调查。完整文件可应要求提供。',
    footer_copyright: '© 2026 Thai Fancy Weaving Co., Ltd. 房产挂牌信息。'
  }
};

let currentLang = 'en';

function setLang(lang) {
  if (!i18n[lang]) return;
  currentLang = lang;

  const htmlEl = document.documentElement;
  htmlEl.lang = lang === 'zh' ? 'zh-Hans' : lang;

  document.querySelectorAll('[data-i18n]').forEach(function(el) {
    const key = el.getAttribute('data-i18n');
    if (i18n[lang][key] !== undefined) {
      el.textContent = i18n[lang][key];
    }
  });

  document.querySelectorAll('.lang-btn').forEach(function(btn) {
    btn.classList.remove('active');
  });
  const activeBtn = document.getElementById('lang-' + lang);
  if (activeBtn) activeBtn.classList.add('active');

  try { localStorage.setItem('preferred-lang', lang); } catch (e) {}
}

(function init() {
  let saved = 'en';
  try { saved = localStorage.getItem('preferred-lang') || 'en'; } catch (e) {}
  if (i18n[saved]) setLang(saved);

  // Animate valuation bars on scroll into view
  const bars = document.querySelectorAll('.val-bar');
  if ('IntersectionObserver' in window) {
    bars.forEach(function(bar) {
      const targetWidth = bar.style.width;
      bar.style.width = '0%';
      const obs = new IntersectionObserver(function(entries) {
        if (entries[0].isIntersecting) {
          bar.style.width = targetWidth;
          obs.disconnect();
        }
      }, { threshold: 0.3 });
      obs.observe(bar);
    });
  }
})();
